---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).

**Inventory**
The inventory system your server uses (e.g. ox_inventory, qb-inventory, esx_inventory).

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Console errors**
If applicable, add any console errors (client or server) related to the issue.

**Additional context**
Add any other context about the problem here.
